### ISSUE TITLE
Integrate mongodb, create a connection string

### ISSUE THREAD

**Issue by dusty3ntity** [dusty3ntity/Scheduler#6]

**Comment by AndriiMakarets** [comment]
Вельми цікаво

**Comment by AndriiMakarets** [comment]
![image](https://user-images.githubusercontent.com/66354655/96592137-be5aba00-12f0-11eb-9f39-67258ead50a5.png)

**Comment by AndriiMakarets** [comment]
як  маю це розуміти?

**Comment by AndriiMakarets** [comment]
Хоча, хочеться робити за мене - будь-ласка. Тільки якось неправильно так робити, коли я вже перемістив завдання в ін прогрес, мені здається.
